### ISSUE TITLE
Metaschema validation fails when loading metaschema from string

### ISSUE THREAD

**Issue by the4thamigo-uk** [miracl/conflate#3]
Currently schema validation against the metaschema requires downloading the metaschema remotely using `validateSchemaTemporary`. This is due to a bug is gojson schema (https://github.com/xeipuuv/gojsonschema/issues/170 and transitively to https://github.com/xeipuuv/gojsonreference/pull/8). When this bug is fixed the code can be reverted to call `validateSchema`

**Comment by andy-miracl** [comment]
will repost under the correct account
